# Starts Redis and Serverless Redis HTTP containers so that Vercel KV has a
# serverless Redis database to access. This compose file is sourced from this
# Github issue comment:
# https://github.com/vercel/storage/issues/281#issuecomment-2067729077

services:
  # This is the local Redis database that will be running on your computer.
  # Within docker it has the hostname `redis` and it exposes the port 6379 to
  # your pc and other containers.
  redis:
    image: redis
    ports:
      - '6379:6379'

  # This is the serverless router that allows the Vercel KV libraries to send
  # queries to the Redis server above (redis:6379). It uses the port 80
  # internally, so it is mapped to an arbitrary port 8079, so that it doesn't
  # conflict with your potential web app on port 80. Think of this as local
  # Vercel KV.
  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: kv_token # This is your local Vercel KV instance's API token (KV_REST_API_TOKEN), and you can change it to anything or keep it as is for development
      SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
